# -*- coding: utf-8 -*-
"""MeuCatalogoFilmes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJCnzB5G3C5PFahkhM4GaSoagqAn5V0Z
"""

from IPython.display import display, HTML
import base64
import json

# --- CONFIGURAÇÃO INICIAL (NOME FIXO: filmes_storage) ---
cor_banner_inicio = "#1a1a1a"
cor_banner_fim = "#2c3e50"

filmes_storage = {
    "Criminal": {"icon": "🔪", "filmes": ["Murder on the Orient Express", "Pulp Fiction", "O agente secreto", "O Colecionador de Ossos"]},
    "Suspense": {"icon": "😰", "filmes": ["Don’t move", "Foi apenas um acidente", "O enfermeiro da noite", "Oito mulheres e um segredo"]},
    "Drama": {"icon": "🎭", "filmes": ["Nomadland", "Vidas Passadas", "O último azul", "Paradise"]},
    "+18": {"icon": "🔞", "filmes": ["A empregada", "Me chame pelo seu nome", "Sex/Life", "Azul é a cor mais quente"]},
    "Documentário": {"icon": "📽️", "filmes": ["Dear Zachary", "Planet Earth", "Alphago", "Age of Samurai"]},
    "Aventura": {"icon": "🧗", "filmes": ["Uncharted", "Fúria de titãs 1 e 2", "Predador", "Kaguya"]},
    "Guerra": {"icon": "⚔️", "filmes": ["Até o último homem", "O resgate do soldado ryan", "A Lista de Schindler", "1917"]},
    "Fantasia": {"icon": "🧙", "filmes": ["Avatar", "Frankenstein", "O troll da montanha", "A torre negra"]},
    "Ficção": {"icon": "👽", "filmes": ["Ruptura", "A grande inundação", "Spaceman", "2001: A Space Odyssey"]},
    "Romance": {"icon": "❤️", "filmes": ["Todo tempo que temos", "O prisma do amor", "Meu Eterno Talvez", "303"]},
    "Comédia Romântica": {"icon": "🥰", "filmes": ["10 Things I Hate About You", "Columbus", "Sleeping with Other People", "The big sick"]},
    "Comédia": {"icon": "😂", "filmes": ["Queime Depois de Ler", "O Dublê", "Residence", "O fantástico senhor raposo"]},
    "Animação": {"icon": "🎨", "filmes": ["Zootopia 2", "Aranhaverso 2", "Cowboy Bebop", "Sussurros do Coração"]},
    "Ação": {"icon": "💥", "filmes": ["Pecadores", "Classe dos herois fracos", "CasHero", "Máquina de guerra"]},
    "Asiático": {"icon": "🍜", "filmes": ["Alquimia das almas", "Se esse amor desaparecesse hoje", "The Handmaiden", "I Want to Eat Your Pancreas"]},
    "Terror": {"icon": "👻", "filmes": ["Donnie darko", "A hora do mal", "It a coisa", "O Iluminado"]},
    "Musical": {"icon": "🎵", "filmes": ["La la land", "Mamma Mia!", "Os Miseráveis", "O Rei do Show"]}
}

cores_lista = ["#e50914", "#ff9800", "#9c27b0", "#333333", "#009688", "#2196f3", "#795548", "#607d8b", "#4caf50", "#e91e63", "#00bcd4", "#673ab7", "#ffc107", "#3f51b5", "#8bc34a", "#f44336", "#00d2ff"]
mapeamento_cores = {cat: cores_lista[i % len(cores_lista)] for i, cat in enumerate(filmes_storage.keys())}

html_base = f'''
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Catálogo de Filmes</title>
    <style>
        :root {{
            --bg-body: #f4f4f4;
            --bg-card: white;
            --text-main: #444;
            --bg-admin: #fff;
            --banner-grad: linear-gradient(135deg, {cor_banner_inicio}, {cor_banner_fim}, #000);
        }}

        body.light-mode {{
            --bg-body: #f4f4f4;
            --bg-card: white;
            --text-main: #444;
            --bg-admin: #fff;
        }}

        body.dark-mode {{
            --bg-body: #121212;
            --bg-card: #1e1e1e;
            --text-main: #e0e0e0;
            --bg-admin: #1e1e1e;
        }}

        body {{ background-color: var(--bg-body); margin: 0; padding-bottom: 100px; font-family: 'Segoe UI', sans-serif; text-align: center; transition: background 0.3s; font-size: 1.05em; }}

        .banner-fino {{
            width: 100%; height: 160px;
            background: var(--banner-grad);
            display: flex; align-items: center; justify-content: center; margin-bottom: 25px;
            color: white; box-shadow: 0 4px 15px rgba(0,0,0,0.3); position: relative;
        }}

        .theme-toggle {{
            position: absolute; top: 20px; right: 30px;
            background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.3);
            color: white; padding: 8px 15px; border-radius: 20px; cursor: pointer;
            font-size: 0.8em; font-weight: bold; transition: 0.3s;
        }}

        .admin-panel {{
            max-width: 1200px; margin: 20px auto; background: var(--bg-admin); padding: 30px; border-radius: 12px;
            display: flex; justify-content: space-between; gap: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            color: var(--text-main);
        }}
        .admin-box {{ flex: 1; display: flex; flex-direction: column; gap: 12px; text-align: left; }}

        .admin-box strong {{ font-size: 1.2em; }}
        input, select, button {{ padding: 14px; border-radius: 8px; border: 1px solid #ccc; font-family: inherit; font-size: 1em; }}

        button {{ cursor: pointer; font-weight: bold; border: none; }}
        .fire-hover {{ transition: box-shadow 0.3s ease; }}
        .fire-hover:hover {{ box-shadow: 0 0 8px 2px var(--btn-color-opaque); }}

        .btn-add {{ background: #28a745; --btn-color-opaque: rgba(40, 167, 69, 0.5); color: white; }}
        .btn-rem {{ background: #dc3545; --btn-color-opaque: rgba(220, 53, 69, 0.5); color: white; }}
        .btn-sort {{ background: #2c3e50; --btn-color-opaque: rgba(44, 62, 80, 0.5); color: white; }}

        #resultado-sorteio {{
            margin-top: 5px; height: 50px; padding: 0 10px; border-radius: 8px; background: rgba(0,0,0,0.05);
            border: 1px dashed #ccc; font-weight: bold; color: var(--text-main);
            font-size: 0.85em;
            display: flex; align-items: center; justify-content: center;
            overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
        }}

        .container {{ max-width: 1200px; margin: 0 auto; text-align: left; padding: 0 20px; }}
        .filme-card {{
            background: var(--bg-card); padding: 18px; border-radius: 8px;
            display: flex; align-items: center; box-shadow: 0 2px 4px rgba(0,0,0,0.05);
            border-left: 6px solid; margin-bottom: 5px; transition: 0.3s;
            color: var(--text-main);
        }}
        .filme-card.visto {{ background-color: #d4edda !important; border-left-color: #28a745 !important; color: #155724; }}

        .cat-row {{ display: flex; justify-content: center; gap: 10px; flex-wrap: wrap; width: 100%; margin-bottom: 15px; }}
        .cat-btn {{ padding: 10px 15px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 0.85em; color: white; }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 15px; margin-top: 20px; }}

        html {{ scroll-behavior: smooth; }}
    </style>
</head>
<body id="topo-pagina" class="dark-mode">
    <div class="banner-fino">
        <h1>MEU CATÁLOGO DE FILMES</h1>
        <button class="theme-toggle" onclick="toggleTheme()">🌓 ALTERAR MODO</button>
    </div>

    <div class="admin-panel">
        <div class="admin-box">
            <strong style="color: #28a745;">➕ ADICIONAR</strong>
            <select id="sel-cat-add"></select>
            <input type="text" id="input-add" placeholder="Nome do filme...">
            <button class="btn-add fire-hover" onclick="adicionarFilme()">SALVAR NOVO</button>
        </div>
        <div style="width: 1px; background: #eee; opacity: 0.3;"></div>
        <div class="admin-box">
            <strong style="color: #dc3545;">➖ REMOVER</strong>
            <select id="sel-cat-rem" onchange="atualizarListaRemover()"></select>
            <select id="sel-filme-rem"><option value="">Escolha a categoria...</option></select>
            <button class="btn-rem fire-hover" onclick="removerFilme()">DELETAR</button>
        </div>
        <div style="width: 1px; background: #eee; opacity: 0.3;"></div>
        <div class="admin-box">
            <strong style="color: #2c3e50;">🎲 SORTEAR</strong>
            <select id="sel-cat-sort"></select>
            <button class="btn-sort fire-hover" onclick="sortearFilme()">O QUE ASSISTIR?</button>
            <div id="resultado-sorteio">Aguardando sorteio...</div>
        </div>
    </div>

    <div id="menu-categorias"></div>
    <div class="container" id="conteudo-catalogo"></div>

    <script>
    const dbInicial = REPLACE_DB_INICIAL;
    const coresMapping = REPLACE_CORES;
    let db = JSON.parse(localStorage.getItem('meuDB')) || dbInicial;
    let sorteadosNaSessao = [];

    function toggleTheme() {{
        const body = document.body;
        body.classList.toggle('dark-mode');
        body.classList.toggle('light-mode');
        localStorage.setItem('theme', body.classList.contains('dark-mode') ? 'dark' : 'light');
    }}

    function carregarTema() {{
        const saved = localStorage.getItem('theme');
        if (saved === 'light') {{
            document.body.classList.remove('dark-mode');
            document.body.classList.add('light-mode');
        }}
    }}

    function scrollToCategory(e, id) {{
        e.preventDefault();
        const el = document.getElementById(id);
        el.scrollIntoView({{ behavior: 'smooth', block: 'center' }});
    }}

    function salvarDB() {{
        localStorage.setItem('meuDB', JSON.stringify(db));
        renderizarTudo();
    }}

    function adicionarFilme() {{
        const cat = document.getElementById('sel-cat-add').value;
        const nome = document.getElementById('input-add').value.trim();
        if (nome) {{
            db[cat].filmes.push(nome);
            document.getElementById('input-add').value = '';
            salvarDB();
        }}
    }}

    function atualizarListaRemover() {{
        const cat = document.getElementById('sel-cat-rem').value;
        const selFilmeRem = document.getElementById('sel-filme-rem');
        let html = '<option value="">Selecione o filme...</option>';
        if (cat && db[cat]) {{
            db[cat].filmes.forEach((filme, idx) => {{
                html += `<option value="${{idx}}">${{filme}}</option>`;
            }});
        }}
        selFilmeRem.innerHTML = html;
    }}

    function removerFilme() {{
        const cat = document.getElementById('sel-cat-rem').value;
        const index = document.getElementById('sel-filme-rem').value;
        if (cat && index !== "") {{
            if (confirm(`Remover "${{db[cat].filmes[index]}}"?`)) {{
                db[cat].filmes.splice(index, 1);
                salvarDB();
            }}
        }}
    }}

    function sortearFilme() {{
        const catAlvo = document.getElementById('sel-cat-sort').value;
        let listaCandidatos = [];
        const naoFoiVisto = (nome) => {{
            const safeId = btoa(unescape(encodeURIComponent(nome))).replace(/[^a-zA-Z0-9]/g, '');
            return !localStorage.getItem('visto-' + safeId);
        }};
        const filtrarEAdicionar = (cat) => {{
            db[cat].filmes.filter(naoFoiVisto).forEach(f => {{
                if (!sorteadosNaSessao.includes(f)) {{
                    listaCandidatos.push({{nome: f, cat: cat}});
                }}
            }});
        }};

        if (catAlvo === "TODOS") {{
            Object.keys(db).forEach(filtrarEAdicionar);
        }} else {{
            filtrarEAdicionar(catAlvo);
        }}

        const resultadoDiv = document.getElementById('resultado-sorteio');

        if (listaCandidatos.length === 0) {{
            if (sorteadosNaSessao.length > 0) {{
                sorteadosNaSessao = [];
                sortearFilme();
                return;
            }}
            resultadoDiv.innerText = "Nada novo!";
            return;
        }}

        const sorteado = listaCandidatos[Math.floor(Math.random() * listaCandidatos.length)];
        sorteadosNaSessao.push(sorteado.nome);

        // --- Formatação: 🎥 Sugestão: Nome (Categoria) ---
        resultadoDiv.innerHTML = `🎥 Sugestão: &nbsp; <strong>${{sorteado.nome}}</strong> &nbsp; (${{sorteado.cat}})`;
    }}

    function marcarVisto(safeId) {{
        const card = document.getElementById('card-' + safeId);
        if (localStorage.getItem('visto-' + safeId)) {{
            localStorage.removeItem('visto-' + safeId);
            card.classList.remove('visto');
        }} else {{
            localStorage.setItem('visto-' + safeId, 'true');
            card.classList.add('visto');
        }}
    }}

    function hexToRgba(hex, opacity) {{
        hex = hex.replace('#', '');
        const r = parseInt(hex.substring(0, 2), 16);
        const g = parseInt(hex.substring(2, 4), 16);
        const b = parseInt(hex.substring(4, 6), 16);
        return `rgba(${{r}}, ${{g}}, ${{b}}, ${{opacity}})`;
    }}

    function renderizarTudo() {{
        const menu = document.getElementById('menu-categorias');
        const conteudo = document.getElementById('conteudo-catalogo');
        const selAdd = document.getElementById('sel-cat-add');
        const selCatRem = document.getElementById('sel-cat-rem');
        const selCatSort = document.getElementById('sel-cat-sort');

        let htmlMenu = '<div class="cat-row">';
        let htmlConteudo = '';
        let htmlOptionsCat = '<option value="">Escolha...</option>';
        let htmlOptionsSort = '<option value="TODOS">Todas as Categorias</option>';

        const keys = Object.keys(db);
        keys.forEach((cat, i) => {{
            const cor = coresMapping[cat];
            const corOpaque = hexToRgba(cor, 0.5);
            const catId = cat.replace(/ /g, '-');
            if (i === 9) htmlMenu += '</div><div class="cat-row">';

            htmlMenu += `<a href="#${{catId}}" onclick="scrollToCategory(event, '${{catId}}')" class="cat-btn fire-hover" style="background-color: ${{cor}}; --btn-color-opaque: ${{corOpaque}};">${{cat.toUpperCase()}}</a>`;
            htmlOptionsCat += `<option value="${{cat}}">${{cat}}</option>`;
            htmlOptionsSort += `<option value="${{cat}}">${{cat}}</option>`;

            htmlConteudo += `<div id="${{catId}}" style="margin-top: 60px; border-bottom: 2px solid ${{cor}}; padding-bottom: 5px; display: flex; align-items: center; justify-content: space-between;">
                                <h3 style="color: ${{cor}}; margin:0; font-size: 1.4em;">${{cat}} ${{db[cat].icon}}</h3>
                                <a href="#topo-pagina" style="text-decoration: none; font-size: 0.8em; color: #aaa;">↑ TOPO</a>
                             </div><div class="grid">`;
            db[cat].filmes.forEach(filme => {{
                const safeId = btoa(unescape(encodeURIComponent(filme))).replace(/[^a-zA-Z0-9]/g, '');
                const visto = localStorage.getItem('visto-' + safeId) ? 'visto' : '';
                const checked = visto ? 'checked' : '';
                htmlConteudo += `<div class="filme-card ${{visto}}" style="border-left-color: ${{cor}};" id="card-${{safeId}}">
                                    <input type="checkbox" class="checkbox-visto" ${{checked}} onchange="marcarVisto('${{safeId}}')">
                                    <a href="https://www.google.com/search?q=${{filme.replace(/ /g, '+')}}+filme" target="_blank" style="text-decoration: none; color: inherit; flex-grow: 1; margin-left:10px;">${{filme}}</a>
                                 </div>`;
            }});
            htmlConteudo += '</div>';
        }});

        menu.innerHTML = htmlMenu + '</div>';
        conteudo.innerHTML = htmlConteudo;
        selAdd.innerHTML = htmlOptionsCat;
        selCatRem.innerHTML = htmlOptionsCat;
        selCatSort.innerHTML = htmlOptionsSort;
        atualizarListaRemover();
    }}
    window.onload = () => {{ carregarTema(); renderizarTudo(); }};
    </script>
</body>
</html>
'''

# Injeção e Salvamento Fixo (NOME: catalogo_filmes.html)
html_final = html_base.replace('REPLACE_DB_INICIAL', json.dumps(filmes_storage))
html_final = html_final.replace('REPLACE_CORES', json.dumps(mapeamento_cores))

with open("catalogo_filmes.html", "w", encoding="utf-8") as f:
    f.write(html_final)

display(HTML(f'''
    <div style="background: #fdfdfd; padding: 30px; border-radius: 15px; border: 2px solid #2c3e50; text-align: center;">
        <h2 style="color: #2c3e50;">Catálogo de Filmes</h2>
        <a href="data:text/html;base64,{base64.b64encode(html_final.encode('utf-8')).decode('utf-8')}" target="_blank" style="background: #2c3e50; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">
            LANÇAR CATÁLOGO COMPLETO 🚀
        </a>
    </div>
'''))